export const CITYS = [
  { key: '지역을 선택하세요', value: '' },
  { key: '강원특별자치도', value: '강원특별자치도' },
  { key: '경기', value: '경기' },
  { key: '경남', value: '경남' },
  { key: '경북', value: '경북' },
  { key: '광주', value: '광주' },
  { key: '대구', value: '대구' },
  { key: '대전', value: '대전' },
  { key: '부산', value: '부산' },
  { key: '서울', value: '서울' },
  { key: '세종특별자치시', value: '세종특별자치시' },
  { key: '울산', value: '울산' },
  { key: '인천', value: '인천' },
  { key: '전남', value: '전남' },
  { key: '전북', value: '전북' },
  { key: '제주특별자치도', value: '제주특별자치도' },
  { key: '충남', value: '충남' },
  { key: '충북', value: '충북' },
];
